### ISSUE TITLE
7. 판매내역 

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#10]
## ☑️ 진행할 작업
판매중/판매완료에 해당하는 상품 리스트를 보여주는 화면을 구성
## 📝 TODO
- [ ] 판매내역에는 판매중, 판매완료 2개의 영역으로 이루어져 있다
- [ ] 해당 상태에 맞는 상품이 없으면 상품이 없다는 문구를 표시
- [ ] 홈화면에 나오는 리스트에 더보기 버튼이 추가된 리스트가 화면에 보여진다
- [ ] 더보기 버튼에는 총 4개의 항목 존재
- 게시글 수정
- 상태 전환 버튼 2개(현재 상태와 더보기 버튼의 나머지 상태 2개는 상호 배타적)
- 삭제
- [ ] 상태전환 버튼을 누르면 그에 맞게 판매내역도 수정
- [ ] 상태 전환 버튼을 누르면 더보기 버튼에 나오는 상태 버튼 이름도 바뀜
- 예) 판매중인 상품의 더보기를 누르면 예약 중/판매완료 
- [ ] 내역에 나오는 아이템을 터치하면 상세화면으로 이동
## ⚙️ 기타
-
