### ISSUE TITLE
8. 관심목록

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#11]
## ☑️ 진행할 작업
관심상품 버튼을 누른 상품의 목록을 보여주는 화면 구성
## 📝 TODO
- [ ] 상단에 카테고리가 나열되는데 전체 카테고리를 제외한 나머지는 관심목록에 있는 상품들의 카테고리가 나열된다
- [ ] 카테고리를 누르면 그에 맞는 상품만 목록에 표시된다
- [ ] 관심상품이 없으면 관심상품이 없다는 문구가 표시된다
- [ ] 리스트의 아이템은 홈화면 스타일을 재사용한다
- [ ] 관심상품으로 등록한 제품의 상세페이지에서 검은하트 아이콘을 다시 누르면 관심목록에서 삭제된다
## ⚙️ 기타
-
