### ISSUE TITLE
9. 채팅

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#12]
## ☑️ 진행할 작업
판매자와 구매자간의 1:1 채팅화면을 구성한다
## 📝 TODO
- [ ] 채팅 목록에 나오는 아이템에는 프로필 사진, 상대방 아이디, 가장 최신 채팅내용, 관련상품 썸네일이 표시된다
- [ ] 채팅 상세화면에 들어가서 메시지를 확인하지 않은 경우에는 확인하지 않은 메시지 갯수를 목록에 같이 표시한다
- [ ] navigation bar 왼쪽에는 뒤로 버튼, 중앙에는 상대방의 아이디, 오른쪽에는 더보기 버튼이 있다
- [ ] bar 아래에는 판매상품의 이미지, 이름, 가격이 표시된다
- [ ] 메시지를 보낼 수 있는 input box가 있는데 메시지가 입력되어야 전송버튼이 활성화 된다
- [ ] 더보기 버튼의 구성
- 알람끄기
  - 설정앱으로 넘어가는 기능
- 신고하기
  - 임의의 이메일 주소로 피드백하는 기능
- 채팅방 나가기
  - alert 이 나오고 이후 채팅방 목록화면으로 나가지면서 해당 채팅방은 목록에서 삭제됨
## ⚙️ 기타
-
