### ISSUE TITLE
10. 내 계정

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#13]
## ☑️ 진행할 작업
로그인, 회원가입 화면을 구성한다
## 📝 TODO
- [ ] 로그인에는 아이디가 필요하지만 회원가입에는 아이디와 현재 위치가 필요하다
- [ ] 사용자 프로필 이미지도 등록이 가능하다(선택기능)
  - [ ] 회원가입/내계정 화면 2가지 화면에서 이미지 등록이 가능
## ⚙️ 기타
-
