### ISSUE TITLE
ViewController 병합 작업

### ISSUE THREAD

**Issue by hyeffie** [codesquad-members-2023-proj02-team04/second-hand-ios#17]
## ☑️ 진행할 작업
홈 상품 목록 화면, 판매 내역 화면, 관심 상품 목록 화면의 view controller 코드 병합 

## 📝 TODO

- [ ] 홈 상품 목록 화면
- [ ] 판매 내역 화면
- [ ] 관심 상품 목록 화면

## ⚙️ 기타
- tab bar controller 일부 코드 수정 필요
