### ISSUE TITLE
로그인 화면 UI 구성

### ISSUE THREAD

**Issue by hyeffie** [codesquad-members-2023-proj02-team04/second-hand-ios#18]
## ☑️ 진행할 작업
로그인 화면 및 컴포넌트 작성

## 📝 TODO
컴포넌트 작성
- [x] 프로필 이미지 버튼
- [x] 깃헙으로 로그인 버튼
- [x] 로그아웃 버튼
- [x] (선택) 아이디 필드 뷰

화면
- [x] 로그인 화면
- [x] 회원가입 정보 입력 화면
- [x] 로그아웃 화면

## ⚙️ 기타
![스크린샷 2023-06-16 02 19 49](https://github.com/codesquad-members-2023-proj02-team04/second-hand-ios/assets/56967908/16540f8e-56c5-4c50-a280-ead91c18f7c5)

**Comment by hyeffie** [comment]
로그아웃 화면은 로그인 화면이랑 같고, 상태에 따라 분기 구현하겠습니다 !
