### ISSUE TITLE
홈화면 목록 api 데이터 표시하기

### ISSUE THREAD

**Issue by hyeffie** [codesquad-members-2023-proj02-team04/second-hand-ios#28]
## ☑️ 진행할 작업
api 로부터 뷰에서 사용할 엔티티를 요청해오고, 로컬에 저장하고, 저장되면 업데이트한다.

## 📝 TODO

- [x] 공통 네트워크 코드 작성
- [x] 하위 타입 작성
- [x] 목록 api 요청 호출 코드 작성 및 출력
- [x] 로컬 저장 (controller)
- [x] 저장에 대한 뷰 업데이트 구현
