### ISSUE TITLE
1. 홈화면

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#4]
## ☑️ 진행할 작업
어플의 첫화면에 나오는 요소를 표시하는 작업을 한다
## 📝 TODO
- [ ] 동네 표시 하는 navigationBar의 leftItem에는 chevron.down 이미지가 동네이름과 같이 표시된다
- [ ] rightItem에는 18개의 카테고리를 보여주는 hamburger button이 존재한다
- [ ] 로그인이 안 되어 있을 경우 chevron.down은 비활성화 되고, 역삼1동을 default값으로 지정한다
- [ ] 로그인이 안되어있을 경우 홈화면을 제외한 나머지 탭을 터치했을때 로그인을 하라는 alert 창을 출력한다
- [ ] 우측 하단에 Floating Action Button을 표시한다
- [ ] 판매 리스트 아이템은 이미지, 제목, 동네, 업로드 시간, 판매상태, 가격, 채팅목록 갯수, 해당상품을 관심목록에 지정한 유저의 수 를 보여준다
- [ ] 채팅과 관심목록은 이력이 없으면 표시하지 않는다
- [ ] 상품은 스크롤 할때 10개 단위로 불러온다
