### ISSUE TITLE
2. 동네설정 화면

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#5]
## ☑️ 진행할 작업
로그인 이후 사용자의 동네를 설정하는 화면을 구성한다
## 📝 TODO
- [ ] 로그인이 된 경우 동네 이름을 터치하면, 내 동네 설정하기 메뉴가 보여진다
- [ ] 그렇지 않으면 버튼을 눌렀을때 역삼1동만 보여진다
- [ ] 내 동네 설정하기 화면으로 이동하면, 최대 2개까지 동네를 설정할 수 있는 화면이 표시되고 기본적으로 최소 1개의 동네는 등록되어 있는 상태이다
- [ ] + 버튼을 누르면 동네 리스트 화면이 나오고, 해당 화면에서 검색창으로 동네를 검색이 가능하다
- [ ] 동네 목록 화면에서 동네를 선택하면 그 즉시 바뀐 동네 화면을 기준으로 한 홈화면으로 넘어간다
- [ ] 기존에 등록된 동네를 삭제할 수 있는데, x 버튼을 눌러서 삭제를 할 경우 alert을 출력한다
- [ ] 만약 기존에 동네가 1개밖에 등록되지 않은 상태에서 삭제를 진행하면 삭제가 진행되지 않고 최소 1개의 동네가 필요하다는 alert을 출력한다
- [ ] 동네 설정화면에서 동네를 선택한 상태에서 닫기 버튼을 누르면 해당 동네의 홈화면으로 이동한다
## ⚙️ 기타
