### ISSUE TITLE
3. 카테고리

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#6]
## ☑️ 진행할 작업
카테고리 화면을 구성한다
## 📝 TODO
- [ ] 홈화면의 navigation bar의 right item을 누르면 18개의 카테고리가 표시된다
- [ ] 이때 화면의 전환에서 오->왼 방향으로 슬라이딩 애니메이션이 보이도록 한다
- [ ] 뒤로 버튼은 직전 화면으로 이동
- [ ] 카테고리를 누르면 현재 동네 홈화면에서 해당 카테고리에 해당하는 제품만 재정렬하여 보여준다
## ⚙️ 기타
