### ISSUE TITLE
4. 상품 등록 화면

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#7]
## ☑️ 진행할 작업
판매할 상품을 등록하는 화면을 구성한다
## 📝 TODO
- [ ] 닫기 버튼은 직전화면으로 이동한다
- [ ] 완료 버튼은 필수 입력값들이 모두 입력되어있는 상태에서 활성화 되도록 한다
- [ ] 이미지는 최대 10장을 불러올 수 있으며, 가로로 스크롤 되며, 최초 등록된 이미지가 대표 사진, 썸네일이 된다
- [ ] 이미지 우측 상단에는 x 버튼이 있어서 삭제가 가능
- [ ] 물건 판매 페이지에서 제목을 입력하면 18개의 카테고리 중에서 3개가 랜덤으로 표시됨
- [ ] 선택하는 순간 즉시 색상이 변하도록 설정
- [ ] 카테고리 오른쪽 chevron.right 버튼을 누르면 카테고리 목록이 나오고 해당 페이지에서 카테고리를 선택하면 그 즉시 선택한 카테고리만 남기고 나머지는 삭제
- [ ] 가격이 입력되지 않으면 가격표시 영역에 '가격없음'으로 나타난다
- [ ] 상세설명의 높이는 가변적이고, 최소 높이는 5줄이다
- [ ] 홈에서 등록된 나의 동네 위치를 판매 상품의 위치로 등록한다
- [ ] 동네 설정 버튼을 누르면 내가 설정한 다른 동네로 바꿀 수 있다
- [ ] 다른 동네를 설정한 후 완료 버튼을 누르면 해당 동네의 홈화면을 표시한다
## ⚙️ 기타
- 만약 대표사진으로 등록된 이미지가 삭제될 경우 그 다음 인덱스의 사진이 대표사진으로 자동 등록 되는 것인지에 대해 명확한 가이드라인이 없기 때문에 협의필요
