### ISSUE TITLE
5. 상품 상세화면 [판매자]

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#8]
## ☑️ 진행할 작업
판매자의 입장에서 보이는 상품 상세 화면을 구성한다
## 📝 TODO
- [ ] 판매자의 상세화면(이하 상세화면) 상단에 있는 navigation bar는 고정된 상태
- [ ] 상단바는 화면 첫 진입시에는 투명, 스크롤이 이루어지면 불투명해지면서 하단에 구분선이 표시됨
- [ ] 뒤로 버튼을 누르면 직전 페이지로 이동
- [ ] 만약 업로드 직후의 상세 페이지로 이동한 경우에는 뒤로 버튼을 누를경우 홈 화면으로 이동하도록 한다
- [ ] 오른쪽의 버튼을 누르면 수정/삭제 화면이 하단에서 나온다
- [ ] 수정버튼은 수정화면으로 이동
- [ ] 삭제 버튼은 alert을 띄운다
- [ ] 화면 하단에는 고정된 bar가 존재하며 관심상품 등록버튼, 대화중인 채팅방 버튼이 표시된다
- [ ] 관심상품 등록 버튼을 누르면 검은색 하트 아이콘으로 전환, 관심상품에 등록됨
- [ ] 가격부분은 선택사항
- [ ] 오른쪽 채팅방 버튼에는 우측에 현재 해당상품과 관련한 채팅방의 갯수를 표시, 없으면 대화중인 채팅방 버튼만 표시, 이때 해당 버튼을 누르면 채팅한 이웃이 없습니다 라는 토스트 메시지 출력
- [ ] 상세화면 상단에 있는 이미지에 이미지 갯수, 현재 이미지 위치를 알려주는 네비게이션이 존재
- [ ] 등록한 이미지와 네비게이션이 잘 구분되게 그라데이션을 이미지에 추가
- [ ] 가로로 스와이프하면 다른 이미지로 전환되며, 마지막 이미지에서는 더이상 전환되지 않는다
- [ ] 상품 상태 버튼을 누르면 판매중, 예약중, 판매완료 3가지 중 선택가능
- [ ] 본문의 내용 구성
- 상품상태
- 제목
- 카테고리
- 업로드 경과 시간
- 설명
- 관심이력, 조회수, 채팅방 정보
- 판매자 정보(아이디, 동네위치)
## ⚙️ 기타
-
