### ISSUE TITLE
6. 상품 상세화면 [구매자]

### ISSUE THREAD

**Issue by ghost** [codesquad-members-2023-proj02-team04/second-hand-ios#9]
## ☑️ 진행할 작업
구매자 입장에서 보이는 상품 상세화면을 구성
## 📝 TODO
- [ ] 상단 네비게이션에 더보기 버튼 없음
- [ ] 상품 상태만 나타내고 변경 불가능
- [ ] 우측 하단에 있는 채팅하기 버튼을 누르면 채팅상세화면으로 즉시 이동
- [ ] 첫 메세지가 보내지기 전까지 실제 채팅방은 생성되지 않음
## ⚙️ 기타
-
